title: My Docs Site
description: Example technical documentation
theme: just-the-docs

url: https://KristinChoudhry.github.io
baseurl: /TechWriting

aux_links:
  "Project on GitHub": "https://github.com/KristinChoudhry/TechWriting"

search_enabled: true
